<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Back to Login Forgot Password Button2 Test Object</name>
   <tag></tag>
   <elementGuidId>e8488adb-e9a3-4032-a0af-f6398d1f7e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;__next&quot;]/div/div/div/div/form/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;__next&quot;]/div/div/div/div/form/div/div/button/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;__next&quot;]/div/div/div/div/form/div/div/button/span</value>
   </webElementProperties>
</WebElementEntity>
